types_include = list(contact = c('contact', 
                                 'contact (ladder start)',
                                 'contact (mix alarm)',
                                 'contact (high freq)',
                                 'contat'), 
                     # contact_mix = c('contact or contact-like', 
                     #                 'contact-like', 
                     #                 'contact or short contact or contact-like', 
                     #                 'contact or short contact',
                     #                 'contact-like or tjup', 
                     #                 'contact (split)',
                     #                 'contactjup', 
                     #                 'contactkrr', 
                     #                 'contactortrruup',
                     #                 'short contact or contact'),
                     short_contact = c('short contact', 
                                       'tjup (short contact)', 
                                       'short contact (ladder)',
                                       't short contact',
                                       'short contact (flat)'),
                     growl = c('growl (upsweep)', 
                               'growl (kraa)', 
                               'growl (kree)', 
                               'growl (wow)',
                               'growl (downsweep)', 
                               'growl (kraa - wow)',
                               'growl (kraa - rise)',
                               'growl (agitaged)', 
                               'growl (agitated)',
                               'growl (rise)',
                               'growl or alarm',
                               'growl (flight)'),
                     growl_low = c('growl',
                                   'grow'),
                     trruup = c('trruup', 
                                'trruup (trruupt)'),
                     tjup = c('tjep',
                              'tjup',
                              'tjup (ladder)',
                              'tjup (pip)'),
                     #          'tjup (short contact)',
                     #          'tjup or contact or contact-like',
                     #          'tjup or contact-like',
                     #          'tjup or kaw',
                     #          'tjup or short contact',
                     #          'tjup or tut',
                     #          'tut'),
                     tja = c('tja', 
                             'tjagrrt', 
                             'tja (tjiep)', 
                             'tjarp', 
                             'trjap',
                             'trjarp',
                             'tje'),
                     alarm = c('alarm',
                               # 'short alarm', 
                               'alarm (downsweep)', 
                               'alarm (viwi)',
                               'alarn',
                               'alarm (rise)',
                               'alarn',
                               'alarm (weird)'),
                     other_tonal = c('dash', 
                                     'dash (long)',
                                     'dash (up)',
                                     'dash (long high)',
                                     'tjup (dash)',
                                     'tonal (long)',
                                     'tonal (short)',
                                     'tonal split'),
                     # other = c('alarm_growl', 
                     #           'growl-contact', 
                     #           'growljup', 
                     #           'krk', 
                     #           'krkaw', 
                     #           'krwp', 
                     #           'mix',
                     #           'mixed', 
                     #           'pre', 
                     #           'tjujup',
                     #           'trr mix',
                     #           'trrkaw',
                     #           'tut or short contact',
                     #           'weird mix'),
                     kaw = c('kaw', 
                             'kew',
                             'short kaw',
                             'flat kaw'),
                     frill = c('friep', 
                               'friwiep', 
                               'piep', 
                               'prjup', 
                               'prrfiew', 
                               'krwiep',
                               'prriew',
                               'tuwiep', 
                               'fjiep',
                               'fliep',
                               'tufriep',
                               'fiep'))
